/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import buscapalavras.BoyerMooreBusca;
import buscapalavras.Cronometro;
import buscapalavras.LerArquivo;
import buscapalavras.Manager;

/**
 *
 * @author matheus
 */
public class BoyerMooreMenu extends javax.swing.JFrame {
    BoyerMooreBusca boyerMoore = new BoyerMooreBusca();
    /**
     * Creates new form BoyerMooreMenu
     */
    public BoyerMooreMenu() {
        initComponents();
        iniciaBusca();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVoltar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        respostaBusca = new javax.swing.JLabel();
        duracaoBusca = new javax.swing.JLabel();
        labelDuracao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setText("Boyer Moore");

        respostaBusca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        respostaBusca.setText("<Aguardando busca>");

        duracaoBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        duracaoBusca.setText("duracaoBusca");

        labelDuracao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDuracao.setText("Duração:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botaoVoltar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDuracao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duracaoBusca))
                    .addComponent(respostaBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTitulo))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(43, 43, 43)
                .addComponent(respostaBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracao)
                    .addComponent(duracaoBusca))
                .addGap(40, 40, 40)
                .addComponent(botaoVoltar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void iniciaBusca(){
        
        boolean resultado;
        Cronometro.setInicio(System.currentTimeMillis());
        resultado = boyerMoore.search(LerArquivo.getTextoCompleto(),Manager.getPalavra());
        Cronometro.setFim(System.currentTimeMillis());
        duracaoBusca.setText(Cronometro.getDuracao());
        
        if(resultado){
            respostaBusca.setText("Palavra encontrada");
        }else{
            respostaBusca.setText("Palavra não encontrada");

        }
    }
    
    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel duracaoBusca;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel respostaBusca;
    // End of variables declaration//GEN-END:variables
}
