/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import buscapalavras.Manager;

/**
 *
 * @author matheus
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoNaive = new javax.swing.JButton();
        botaoRabinKarp = new javax.swing.JButton();
        botaoKMP = new javax.swing.JButton();
        botaoBoyerMoore = new javax.swing.JButton();
        campoPalavraChave = new javax.swing.JTextField();
        labelPlavraChave = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        duracaoLeitura = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoNaive.setText("Naive");
        botaoNaive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNaiveActionPerformed(evt);
            }
        });

        botaoRabinKarp.setText("Rabin Karp");
        botaoRabinKarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRabinKarpActionPerformed(evt);
            }
        });

        botaoKMP.setText("KMP");
        botaoKMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoKMPActionPerformed(evt);
            }
        });

        botaoBoyerMoore.setText("Boyer-Moore");
        botaoBoyerMoore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBoyerMooreActionPerformed(evt);
            }
        });

        labelPlavraChave.setText("Palavra Chave:");

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setText("Buscando Palavras");

        duracaoLeitura.setText("duracaoLeitura");

        jLabel1.setText("Tempo de leitura:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPlavraChave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoPalavraChave)
                                    .addComponent(botaoNaive, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(botaoRabinKarp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoKMP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoBoyerMoore, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(duracaoLeitura))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(labelTitulo)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(labelTitulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlavraChave))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botaoNaive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRabinKarp)
                        .addGap(7, 7, 7)
                        .addComponent(botaoKMP)
                        .addGap(7, 7, 7)
                        .addComponent(botaoBoyerMoore)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(duracaoLeitura))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setDuracaoLeitura(String duracaoLeitura) {
        this.duracaoLeitura.setText(duracaoLeitura);
    }
    
    private void botaoBoyerMooreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBoyerMooreActionPerformed
        Manager.setPalavra(campoPalavraChave.getText());
        new BoyerMooreMenu().setVisible(true);
    }//GEN-LAST:event_botaoBoyerMooreActionPerformed

    private void botaoKMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoKMPActionPerformed
        Manager.setPalavra(campoPalavraChave.getText());
        new KnuthMorrisPartMenu().setVisible(true);
    }//GEN-LAST:event_botaoKMPActionPerformed

    private void botaoRabinKarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRabinKarpActionPerformed
        Manager.setPalavra(campoPalavraChave.getText());
        new RabinKarpMenu().setVisible(true);
    }//GEN-LAST:event_botaoRabinKarpActionPerformed

    private void botaoNaiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNaiveActionPerformed
        Manager.setPalavra(campoPalavraChave.getText());
        new NaiveMenu().setVisible(true);
    }//GEN-LAST:event_botaoNaiveActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBoyerMoore;
    private javax.swing.JButton botaoKMP;
    private javax.swing.JButton botaoNaive;
    private javax.swing.JButton botaoRabinKarp;
    private javax.swing.JTextField campoPalavraChave;
    private javax.swing.JLabel duracaoLeitura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelPlavraChave;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
