/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscapalavras;

/**
 *
 * @author matheus
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoNaive = new javax.swing.JButton();
        botaoRabinKarp = new javax.swing.JButton();
        botaoKMP = new javax.swing.JButton();
        botaoBoyerMoore = new javax.swing.JButton();
        campoPalavraChave = new javax.swing.JTextField();
        labelPlavraChave = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoNaive.setText("Naive");
        botaoNaive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNaiveActionPerformed(evt);
            }
        });

        botaoRabinKarp.setText("Rabin Karp");
        botaoRabinKarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRabinKarpActionPerformed(evt);
            }
        });

        botaoKMP.setText("KMP");
        botaoKMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoKMPActionPerformed(evt);
            }
        });

        botaoBoyerMoore.setText("Boyer-Moore");
        botaoBoyerMoore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBoyerMooreActionPerformed(evt);
            }
        });

        labelPlavraChave.setText("Palavra Chave:");

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setText("Buscando Palavras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoRabinKarp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoNaive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoKMP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoBoyerMoore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelPlavraChave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitulo)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlavraChave)
                    .addComponent(campoPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(botaoNaive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRabinKarp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoKMP)
                .addGap(9, 9, 9)
                .addComponent(botaoBoyerMoore)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNaiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNaiveActionPerformed
        this.setVisible(false);
        Manager.setPalavra(campoPalavraChave.getText());
        new NaiveMenu().setVisible(true);
    }//GEN-LAST:event_botaoNaiveActionPerformed

    private void botaoRabinKarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRabinKarpActionPerformed
        this.setVisible(false);
        Manager.setPalavra(campoPalavraChave.getText());
        new RabinKarpMenu().setVisible(true);
    }//GEN-LAST:event_botaoRabinKarpActionPerformed

    private void botaoKMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoKMPActionPerformed
        this.setVisible(false);
        Manager.setPalavra(campoPalavraChave.getText());
        new KnuthMorrisPartMenu().setVisible(true);
    }//GEN-LAST:event_botaoKMPActionPerformed

    private void botaoBoyerMooreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBoyerMooreActionPerformed
        this.setVisible(false);
        Manager.setPalavra(campoPalavraChave.getText());
        new BoyerMooreMenu().setVisible(true);
    }//GEN-LAST:event_botaoBoyerMooreActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBoyerMoore;
    private javax.swing.JButton botaoKMP;
    private javax.swing.JButton botaoNaive;
    private javax.swing.JButton botaoRabinKarp;
    private javax.swing.JTextField campoPalavraChave;
    private javax.swing.JLabel labelPlavraChave;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
